/* Copyright 2026 Johan Denoyer F4WAT
 * https://github.com/jdenoy
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 */

/*
 * EPIRB 406 (RX only) - decodes first-generation Cospas-Sarsat 406 MHz beacon
 * messages on the radio. Tune the VFO (FM, wide; 406.031 MHz covers the
 * 406.025-406.040 channels, or a test generator's frequency), then launch.
 *
 * The receiver is switched to RAW (RX HPF300 / LPF3K / de-emphasis and AFC off)
 * and the RX audio is left on: it reaches PA4 (the voice DAC pin, unused while
 * voice is disabled), held at mid-scale by the MCU DAC (unbuffered) and sampled
 * on ADC channel 4 at 9.6 kHz, timed from
 * SysTick, from the moment RSSI shows a burst. Samples go straight into dec406
 * (see README.md); the last decoded message stays on screen.
 *
 * Keys (UV-K5 and UV-K1): UP/DOWN tune +/-5 kHz from the VFO (up to +/-50 kHz,
 *   while the app runs; direction as set by nav_dir) · 5 back to the VFO frequency
 *   MENU clear · EXIT quit. The speaker plays the bursts: lower the volume.
 * The loader re-runs RADIO_SetupRegisters on exit; the app restores the ADC,
 * PA4, the DAC and its clock itself.
 * Screen texts and protocol names are read-only assets (gen_assets.py, API
 * level 2), kept out of the 4 KiB overlay.
 */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "../app_api.h"
#include "epirb406_assets.h"   /* generated by gen_assets.py (title carries APP_VER) */
#include "dec406.c"

/* ---- MCU registers (PY32F071, core and SysTick at 48 MHz, 10 ms period) ---- */
#define SYST_LOAD   (*(volatile uint32_t *)0xE000E014u)
#define SYST_VAL    (*(volatile uint32_t *)0xE000E018u)
#define ADC_SR      (*(volatile uint32_t *)0x40012400u)
#define ADC_CR2     (*(volatile uint32_t *)0x40012408u)
#define ADC_SMPR3   (*(volatile uint32_t *)0x40012414u)
#define ADC_SQR3    (*(volatile uint32_t *)0x40012438u)
#define ADC_DR      (*(volatile uint32_t *)0x40012450u)
#define GPIOA_MODER (*(volatile uint32_t *)0x50000000u)
#define DAC_CR      (*(volatile uint32_t *)0x40007400u)
#define DAC_SWTRIGR (*(volatile uint32_t *)0x40007404u)
#define DAC_DHR12R1 (*(volatile uint32_t *)0x40007408u)
#define RCC_APBENR1 (*(volatile uint32_t *)0x4002103Cu)
#define RCC_DACEN   (1u << 29)
/* DAC channel 1 on, output buffer off, software trigger (TSEL1 = 111) */
#define DAC_CR_BIAS ((1u << 0) | (1u << 1) | (1u << 2) | (7u << 3))
#define BIAS_CODE   2048u
#define ADC_SR_EOC     (1u << 1)
#define ADC_CR2_START  ((1u << 22) | (1u << 20))   /* SWSTART | EXTTRIG */
#define SMP8_POS       24u
#define SMP4_POS       12u
#define ADC_CH_PA4     4u
#define CYC_PER_SAMPLE (48000000u / DEC406_FS)     /* 5000 */
#define CAP_MAX_CYC    (48000000u / 1000u * 900u)  /* 900 ms after trigger */

/* ---- BK4829 RAW receive ---- */
#define REG_2B      0x2B
#define REG_73      0x73
#define REG_30      0x30   /* 0 then back: VCO recalibration, relock on the new frequency */
#define REG_38      0x38   /* RX frequency, 10 Hz units, low 16 bits  */
#define REG_39      0x39   /* RX frequency, high 16 bits              */
#define STEP_10HZ   500    /* 5 kHz                                   */
#define OFF_MAX     10     /* +/- 10 steps = +/- 50 kHz               */

#define TRIG_DB     10
#define REARM_DB    5
#define COOL_MS     1500
#define TICK_MS     50

/* The app state in one struct: a function loads one base address instead of one
 * literal-pool word per global. Words, then bytes, then halfwords, so every field
 * stays within the Thumb load/store immediate ranges (ldrb <= 31, ldrh <= 62,
 * ldr <= 124). The loader zeroes the overlay (.bss) at every launch. */
static struct {
    const app_api_t *A;
    uint32_t vfoFreq;                  /* VFO RX frequency at launch, 10 Hz units  */
    int32_t  floorQ;                   /* noise floor, dBm x64                     */
    uint32_t tPrev, tCyc;              /* SysTick cycle counter                    */
    uint8_t  have, seq, prevKey, lastErr;
    int8_t   offSteps;                 /* tuning offset from the VFO, 5 kHz steps  */
    bool     running;
    int16_t  rssi, burstRssi;          /* current RSSI, RSSI of the last burst     */
    uint16_t nSync, nFail;
    uint32_t savedSqr3, savedSmpr3, savedModer, savedDac, savedRcc, savedDhr;
    dec406_info_t last;                /* last decoded message                     */
} g;
static dec406_t d;
static char     str[34];

/* ---- formatting ---- */
static char *put(char *o,const char *s){ while(*s)*o++=*s++; return o; }
/* Formatting by repeated subtraction: no division, so no __udivsi3 in the
 * 4 KiB overlay. Values printed stay below 100000. */
static uint8_t sub(uint32_t *v,uint32_t d){ uint8_t q=0; while(*v>=d){ *v-=d; q++; } return q; }
static char *puti(char *o,int32_t v){
    static const uint16_t P10[]={10000u,1000u,100u,10u,1u};
    uint32_t u;
    if(v<0){*o++='-';u=(uint32_t)(-v);} else u=(uint32_t)v;
    bool lead=false;
    for(uint8_t i=0;i<5;i++){
        uint8_t c=sub(&u,P10[i]);
        if(c||lead||i==4u){ *o++=(char)('0'+c); lead=true; }
    }
    return o;
}
/* arc seconds -> "49.27111" (5 decimals, truncated) followed by the hemisphere */
static char *putPos(char *o,int32_t s,char pos,char neg){
    uint32_t a=(uint32_t)(s<0?-s:s);
    o=puti(o,sub(&a,3600u)); *o++='.';
    for(uint8_t k=0;k<5;k++){ a*=10u; *o++=(char)('0'+sub(&a,3600u)); }
    *o++= s<0?neg:pos;
    return o;
}
static void tiny(uint8_t x,uint8_t y,char *end){ *end='\0'; g.A->print_tiny(str,x,y,false,true); }
static void line(uint8_t l,char *end){ *end='\0'; g.A->print_normal(str,0,0,l); }

/* ---- tuning: offset the RX frequency from the VFO (restored by the loader on exit) ---- */
static void tune(void){
    uint32_t f=(uint32_t)((int32_t)g.vfoFreq+(int32_t)g.offSteps*STEP_10HZ);
    g.A->bk_write(REG_38,(uint16_t)(f&0xFFFFu));
    g.A->bk_write(REG_39,(uint16_t)(f>>16));
    uint16_t r30=g.A->bk_read(REG_30);
    g.A->bk_write(REG_30,0);
    g.A->bk_write(REG_30,r30);
}
/* "433.645" from 10 Hz units, rounded to the kHz, without division */
static char *putFreq(char *o,uint32_t f){
    uint16_t mhz=0;
    f+=50u;
    while(f>=100000u){ f-=100000u; mhz++; }
    o=puti(o,mhz); *o++='.';
    *o++=(char)('0'+sub(&f,10000u)); *o++=(char)('0'+sub(&f,1000u)); *o++=(char)('0'+sub(&f,100u));
    return o;
}

/* ---- SysTick cycle counter (call at least every 10 ms) ---- */
static void clkStart(void){ g.tPrev=SYST_VAL; g.tCyc=0; }
static uint32_t clkCyc(void){
    uint32_t v=SYST_VAL;
    g.tCyc += (v<=g.tPrev) ? g.tPrev-v : g.tPrev+(SYST_LOAD+1u-v);
    g.tPrev=v;
    return g.tCyc;
}

/* ---- PA4 bias: the pin has no DC reference of its own (AC-coupled audio), so
 * 9.6 kHz sampling dragged it to 0 V and clipped half the message (406 Lab scope).
 * The MCU DAC on PA4, output buffer off, at mid-scale, holds it at ~VDD/2.
 * Set for the whole run, restored on exit. ---- */
static void biasOn(void){
    GPIOA_MODER=g.savedModer|(3u<<8);           /* PA4 analog                     */
    RCC_APBENR1=g.savedRcc|RCC_DACEN;
    DAC_CR=DAC_CR_BIAS;
    DAC_DHR12R1=BIAS_CODE;
    DAC_SWTRIGR=1u;                           /* DHR -> DOR                     */
}
static void biasOff(void){ DAC_CR=g.savedDac; DAC_DHR12R1=g.savedDhr; RCC_APBENR1=g.savedRcc; GPIOA_MODER=g.savedModer; }

/* ---- ADC on PA4 (channel 4); channel 8 (battery) restored afterwards ---- */
static void adcSelPA4(void){
    ADC_SMPR3=(g.savedSmpr3&~(7u<<SMP4_POS))|(((g.savedSmpr3>>SMP8_POS)&7u)<<SMP4_POS);
    ADC_SQR3=(g.savedSqr3&~0x1Fu)|ADC_CH_PA4;
}
static void adcRestore(void){ ADC_SQR3=g.savedSqr3; ADC_SMPR3=g.savedSmpr3; }
static uint16_t adcRead(void){
    ADC_CR2|=ADC_CR2_START;
    for(uint16_t n=0; !(ADC_SR&ADC_SR_EOC) && n<2000u; n++){}
    return (uint16_t)(ADC_DR&0x0FFFu);
}

/* ---- one burst: sample PA4 at 9.6 kHz into the decoder ---- */
static void capture(void){
    dec406_init(&d,true);        /* INT: integrate the discriminator pulses */
    adcSelPA4();
    clkStart();
    uint32_t next=0;
    bool done=false;
    while(next<CAP_MAX_CYC){
        while(clkCyc()<next){}
        if(dec406_push(&d,adcRead())){ done=true; break; }
        next+=CYC_PER_SAMPLE;
    }
    adcRestore();

    if(!done){ g.nFail++; g.lastErr = d.state==DEC406_DATA ? 2u : 1u; return; }  /* 1 no sync, 2 cut */
    g.nSync++; g.lastErr=0;
    dec406_parse(&d,&g.last);
    g.burstRssi=g.rssi;          /* RSSI at the trigger (not updated while sampling) */
    g.seq++;
    g.have=1;
}

/* ---- display ---- */
static void draw(void){
    /* The UI texts live in the assets: one read per frame into this word-aligned
     * stack block, so each text costs a 2-byte sp-relative add instead of a
     * literal and its pool word (gen_assets.py keeps every offset aligned). */
    char s[UI_SIZE] __attribute__((aligned(4)));
    char *o;
    g.A->asset_read(0,s,UI_SIZE);
    g.A->display_clear();
    g.A->status_clear();
    g.A->print_inverse(s+T_TITLE,2,0,true,true,(uint8_t)(2u+T_TITLE_CHARS*4u));
    g.A->draw_battery();

    if(!g.have){
        o=put(str,s+T_WAIT); line(1,o);
    } else {
        const dec406_info_t *in=&g.last;
        o=put(str,in->id); line(0,o);                                   /* 15-hex ID */
        o=puti(str,in->country); *o++=' ';
        /* protocol name straight from the assets: 16 location names (bits 37-40),
         * then 8 user names (bits 37-39); the entry's NUL padding ends the line */
        uint8_t n=in->userProto ? (uint8_t)(16u+(in->proto&7u)) : (uint8_t)(in->proto&15u);
        o+=g.A->asset_read((uint16_t)(T_PROTO+n*T_PROTO_STRIDE),o,T_PROTO_STRIDE);
        line(1,o);
        if(in->hasPos){ o=putPos(str,in->latS,'N','S'); *o++=' '; o=putPos(o,in->lonS,'E','W'); }
        else o=put(str,s+T_NOPOS);
        line(2,o);

        o=str;
        if(in->selftest) o=put(o,s+T_SELFTEST);
        o=put(o,in->longMsg?s+T_LONG:s+T_SHORT);
        o=put(o,s+T_BCH); o=put(o,in->bch1?s+T_OK:s+T_ERR); *o++='/'; o=put(o,in->bch2?s+T_OK:s+T_ERR);
        tiny(0,33,o);
        o=str; *o++='#'; o=puti(o,g.seq); *o++=' '; o=puti(o,g.burstRssi); o=put(o,s+T_DBM);
        if(in->longMsg){ o=put(o,in->internalPos?s+T_INT:s+T_EXT); if(in->homing) o=put(o,s+T_HOMING); }
        if(in->hasPos && !in->hasFine) o=put(o,s+T_COARSE);
        if(in->idRaw) o=put(o,s+T_RAWID);
        tiny(0,40,o);
    }

    o=putFreq(str,g.vfoFreq+(uint32_t)((int32_t)g.offSteps*STEP_10HZ));
    if(g.offSteps){ *o++=' '; if(g.offSteps>0) *o++='+'; o=puti(o,(int32_t)g.offSteps*5); o=put(o,s+T_KHZ); }
    tiny(0,26,o);

    o=puti(str,g.rssi); *o++='/'; o=puti(o,g.floorQ/64); o=put(o,s+T_DBMOK); o=puti(o,g.nSync);
    o=put(o,s+T_ERRS); o=puti(o,g.nFail);
    if(g.lastErr) o=put(o,g.lastErr==1u?s+T_NOSYNC:s+T_CUT);
    tiny(0,48,o);
}

/* ---- input ---- */
static void handleKeys(void){
    uint8_t key=g.A->get_key();
    if(key==APP_KEY_INVALID||key==g.prevKey){ g.prevKey=key; return; }
    g.prevKey=key;
    switch(key){
        case APP_KEY_EXIT: g.running=false; break;
        case APP_KEY_5:    g.offSteps=0; tune(); break;
        case APP_KEY_MENU: g.have=0; g.nSync=g.nFail=0; g.lastErr=0; break;
        case APP_KEY_UP:
        case APP_KEY_DOWN: {
            int8_t n=(int8_t)(g.offSteps+g.A->nav_dir(key));
            if(n>=-OFF_MAX && n<=OFF_MAX){ g.offSteps=n; tune(); }
            break; }
        default: break;
    }
}

static void cooldown(void){
    for(uint16_t ms=0; ms<COOL_MS; ms+=10){
        if(g.A->rssi_dbm() < g.floorQ/64+REARM_DB) break;
        g.A->delay_ms(10);
    }
}

__attribute__((section(".text.entry"),used))
void app_main(const app_api_t *api){
    g.A=api;
    g.prevKey=APP_KEY_INVALID;   /* the rest of g starts at 0 (overlay zeroed by the loader) */

    g.savedSqr3=ADC_SQR3; g.savedSmpr3=ADC_SMPR3; g.savedModer=GPIOA_MODER; g.savedDac=DAC_CR;
    g.savedRcc=RCC_APBENR1; g.savedDhr=DAC_DHR12R1;
    biasOn();
    g.A->backlight_on();
    g.vfoFreq=g.A->rx_freq();
    g.A->bk_write(REG_2B,(uint16_t)((g.A->bk_read(REG_2B)|0x0700u)&~0x0007u));
    g.A->bk_write(REG_73,(uint16_t)(g.A->bk_read(REG_73)|0x0010u));
    g.A->audio_path(true);
    g.A->set_af(APP_AF_FM);
    g.A->delay_ms(50);

    int32_t f=0;
    for(uint8_t i=0;i<16;i++){ f+=g.A->rssi_dbm(); g.A->delay_ms(5); }
    g.floorQ=f*4;

    g.running=true;
    while(g.running){
        for(uint8_t i=0;i<TICK_MS;i++){
            g.rssi=g.A->rssi_dbm();
            if(g.rssi>=g.floorQ/64+TRIG_DB){
                capture();
                draw(); g.A->blit_status(); g.A->blit_full();
                cooldown();
                break;
            }
            g.floorQ+=((int32_t)g.rssi*64-g.floorQ)/64;
            g.A->delay_ms(1);
        }
        handleKeys();
        if(!g.running) break;
        draw();
        g.A->blit_status();
        g.A->blit_full();
        g.A->battery_sample();
        g.A->backlight_on();         /* keep the screen lit while waiting for bursts (and after a key) */
    }

    biasOff();                   /* the ADC is already restored after each capture */
    g.A->set_af(APP_AF_MUTE);
    g.A->audio_path(false);
}
