/* Copyright 2026 Armel F4HWN
 * https://github.com/armel
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 */

/*
 * Broadcast FM — overlay app. Sovereign: drives the BK1080 directly and owns the
 * radio while running (NO BK4819 dual-watch, unlike the resident FM). Reimplements
 * the full resident FM (fm.c / UI_DisplayFM) - VFO + 48 memories - sharing the
 * resident channel table (gFM_Channels) and config (gEeprom.FM_*), committed to
 * EEPROM on exit. The BK1080 audio is a hardware path, so playback needs no CPU loop.
 *
 * Keys (iso legacy): 0-9 = frequency (VFO) / channel (MR) entry · UP/DOWN = tune /
 *   channel step · STAR = manual scan · F+STAR = auto-scan (stores 48) · MENU = save
 *   (VFO) / delete (MR) · F+1 = band · F+3 = VFO<->MR · F+0 / EXIT = quit.
 */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "../app_api.h"
#include "fm_assets.h"   /* generated by gen_assets.py */

#define STEP        1
#define SCAN_SETTLE 100
#define CHMAX       APP_FM_CH_MAX
#define NAME_LEN    16u

enum { MENU_NONE, MENU_DELETE, MENU_NAME, MENU_LIVE, MENU_SAVE };

/* All the state in one struct: Thumb-1 code then reaches every field from a
 * single base address (one literal per function instead of one per global),
 * byte fields (st's included) first so their offsets fit ldrb's 0..31
 * immediate. The overlay is zeroed by the loader at each launch. */
struct globals {
    app_fm_state_t st;       /* freq_playing, sel_freq, band, is_mr, sel_ch */
    uint8_t  chPos, savePos, inIdx;
    int8_t   scanState;      /* 0 = off, +1 up, -1 down (non-blocking) */
    bool     autoScan, foundFreq, askSave, askDelete, fArm, running;
    bool     liveRssi, liveEdit, liveChoice, nameEdit, autoConfirm, upper;
    uint8_t  inBox[4];
    uint8_t  menuMode, rssiLevel, namePos, nameKey, nameTap;
    char     name[NAME_LEN];
    uint16_t lo, hi;
    uint16_t scanTimer;      /* ms until the next scan step */
    uint32_t rssiTick, nameTick;
    const app_api_t *api;
    uint16_t *ch;            /* shared gFM_Channels[48] */
};
static struct globals g;
#define A (g.api)

_Static_assert(offsetof(struct globals, inBox) + 4u <= 32u, "byte fields out of ldrb range");

/* Decimal digits of v (< 10000), no leading zeros, by subtracting the places:
 * no division is linked. */
static char *putu(char *o, uint16_t v)
{
    uint16_t place[PLACE_LEN / 2u];
    A->asset_read(PLACE, place, sizeof(place));
    bool lead = true;
    for (uint8_t i = 0; i < PLACE_LEN / 2u; i++) {
        uint8_t d = 0;
        while (v >= place[i]) { v -= place[i]; d++; }
        if (d || i == PLACE_LEN / 2u - 1u) lead = false;
        if (!lead) *o++ = (char)('0' + d);
    }
    return o;
}

/* Texts, band names and the F icon are read-only assets (gen_assets.py).
 * put_t() copies a text to o (a buffer of at least TEXT_MAX bytes) and returns
 * its end. */
static char *put_t(char *o, uint16_t off){ A->asset_read(off,o,TEXT_MAX); while(*o)o++; return o; }

static void bandLimits(void){ g.lo=A->fm_lo(g.st.band); g.hi=A->fm_hi(g.st.band); }
static uint16_t wrap(uint16_t f){ if(f<g.lo)return g.hi; if(f>g.hi)return g.lo; return f; }
static void tune(void){ A->fm_set_freq(g.st.freq_playing, g.st.band); }
static void loadName(uint8_t channel)
{
    A->fm_name_load(channel,g.name,NAME_LEN);
    if(!g.name[0]){
        char *o=g.name; uint8_t n=(uint8_t)(channel+1u); o=put_t(o,T_CH);
        *o++=(char)('0'+n/10u); *o++=(char)('0'+n%10u); *o='\0';
    }
}

static void invalidateRssi(void){ g.rssiLevel=0xFFu; }
static void sampleRssi(void)
{
    uint8_t r=A->fm_rssi_raw(), level;
    if(r<10u) level=0u; else if(r>=50u) level=5u; else level=(uint8_t)(1u+(r-10u)*4u/40u);
    if(g.rssiLevel<=5u){
        if(level>g.rssiLevel && r<(uint8_t)(10u*(g.rssiLevel+1u)+2u)) return;
        if(level<g.rssiLevel && r>(uint8_t)(10u*g.rssiLevel-2u)) return;
    }
    g.rssiLevel=level;
}

static bool validCh(uint8_t c){ return c<CHMAX && g.ch[c]>=g.lo && g.ch[c]<g.hi; }
static uint8_t findNext(uint8_t c, int8_t dir)
{
    for(uint8_t i=0;i<CHMAX;i++){
        if(c==0xFF) c=CHMAX-1;
        else if(c>=CHMAX) c=0;
        if(validCh(c)) return c;
        c=(uint8_t)(c+dir);
    }
    return 0xFF;
}
static int configChannel(void)
{
    g.st.freq_playing=g.st.sel_freq;
    if(g.st.is_mr){
        uint8_t c=findNext(g.st.sel_ch,+1);
        if(c==0xFF){ g.st.is_mr=false; return -1; }
        g.st.sel_ch=c; g.st.freq_playing=g.ch[c];
    }
    return 0;
}

/* ---- drawing (mirror UI_DisplayFM) ---- */
/* append a zero-padded 2-digit number (1..99), return the end pointer */
static char *num2(char *o, uint8_t n){ if(n<10)*o++='0'; return putu(o,n); }

static void draw(void)
{
    app_fm_view_t v;
    v.freq_playing=g.st.freq_playing; v.band=g.st.band; v.is_mr=g.st.is_mr;
    v.sel_ch=g.st.sel_ch; v.scan_state=g.scanState; v.auto_scan=g.autoScan;
    v.ch_pos=g.chPos; v.save_pos=g.savePos; v.input_len=g.inIdx;
    for(uint8_t i=0;i<4u;i++) v.input_digits[i]=g.inBox[i];
    v.menu_mode=g.menuMode; v.rssi_level=g.rssiLevel; v.f_arm=g.fArm;
    v.flags=0u; v.editor_mode=1u;
    if(g.askSave) v.flags|=APP_FM_VIEW_ASK_SAVE;
    if(g.askDelete) v.flags|=APP_FM_VIEW_ASK_DELETE;
    if(g.nameEdit) v.flags|=APP_FM_VIEW_NAME_EDIT;
    if(g.autoConfirm) v.flags|=APP_FM_VIEW_AUTO_CONFIRM;
    if(g.liveEdit) v.flags|=APP_FM_VIEW_LIVE_EDIT;
    if(g.liveRssi) v.flags|=APP_FM_VIEW_LIVE_RSSI;
    if(g.liveChoice) v.flags|=APP_FM_VIEW_LIVE_CHOICE;
    if(g.upper) v.flags|=APP_FM_VIEW_EDITOR_UPPER;
    if(g.st.is_mr && !g.nameEdit) loadName(g.st.sel_ch);
    for(uint8_t i=0;i<NAME_LEN;i++) v.name[i]=g.name[i];
    A->fm_draw_gogu(&v);
}
static void show(void){ draw(); A->blit_status(); A->blit_full(); }

/* ---- non-blocking scan state machine (mirrors ACTION_Scan_FM / FM_Play / FM_Tune) ---- */
static void scanTuneNext(void)   /* FM_Tune(freq, scanState, false): step + mute + settle */
{
    A->fm_mute(true);
    g.foundFreq=false;
    g.st.freq_playing=wrap((uint16_t)(g.st.freq_playing+g.scanState));
    tune();
    invalidateRssi();
    g.scanTimer=SCAN_SETTLE;
}
static void stopScan(void)       /* FM_PlayAndUpdate */
{
    if(g.autoScan){ g.st.is_mr=true; g.st.sel_ch=0; }
    g.scanState=0; g.autoScan=false;
    configChannel();
    tune();
    A->fm_mute(false);
}
static void scanStep(void)       /* FM_Play: one step when the settle timer expires */
{
    if(A->fm_valid(g.st.freq_playing,g.lo)==0){      /* station locked */
        if(!g.autoScan){
            g.scanState=0; g.foundFreq=true;
            if(!g.st.is_mr) g.st.sel_freq=g.st.freq_playing;
            A->fm_mute(false);                       /* audio on */
            return;
        }
        if(g.chPos<CHMAX) g.ch[g.chPos++]=g.st.freq_playing;
        if(g.chPos>=CHMAX){ stopScan(); return; }
    }
    if(g.autoScan && g.st.freq_playing>=A->fm_hi(1)){ stopScan(); return; }
    scanTuneNext();
}
static void startManual(int8_t dir)
{
    if(g.scanState){ stopScan(); return; }           /* STAR toggles */
    g.autoScan=false; g.chPos=0; g.scanState=dir;
    scanTuneNext();
}
static void startAuto(void)
{
    if(g.scanState){ stopScan(); return; }
    g.autoScan=true; g.chPos=0; g.scanState=+1;
    for(uint8_t i=0;i<CHMAX;i++) g.ch[i]=0xFFFF;
    A->fm_names_erase();
    g.st.freq_playing=g.lo;
    A->fm_mute(true);
    tune();                                          /* FM_Tune(lo,1,true): no step */
    g.scanTimer=SCAN_SETTLE;
}

/* ---- digit entry ---- */
static void digit(uint8_t d)
{
    if(g.askDelete||g.scanState) return;
    if(g.askSave || g.st.is_mr){                     /* 2-digit channel */
        if(g.inIdx<2) g.inBox[g.inIdx++]=d;
        if(g.inIdx>=2){
            uint8_t c=(uint8_t)(g.inBox[0]*10+g.inBox[1]-1); g.inIdx=0;
            if(g.askSave){ if(c<CHMAX) g.savePos=c; }
            else if(validCh(c)){ g.st.sel_ch=c; g.st.freq_playing=g.ch[c]; tune(); invalidateRssi(); }
        }
        return;
    }
    /* VFO frequency: 4 digits, with the leading-digit>1 zero-pad trick */
    g.inBox[g.inIdx++]=d;
    if(g.inIdx==1 && g.inBox[0]>1){ g.inBox[1]=g.inBox[0]; g.inBox[0]=0; g.inIdx=2; }
    else if(g.inIdx>3){
        uint16_t f=(uint16_t)(g.inBox[0]*1000+g.inBox[1]*100+g.inBox[2]*10+g.inBox[3]); g.inIdx=0;
        if(f>=g.lo && f<=g.hi){ g.st.sel_freq=f; g.st.freq_playing=f; tune(); invalidateRssi(); }
    }
}

static void menuMove(int8_t dir)
{
    if(!g.st.is_mr)
        g.menuMode=(g.menuMode==MENU_LIVE)?MENU_SAVE:MENU_LIVE;
    else if(dir>0)
        g.menuMode=(g.menuMode==MENU_LIVE)?MENU_NAME:(g.menuMode==MENU_NAME)?MENU_DELETE:MENU_LIVE;
    else
        g.menuMode=(g.menuMode==MENU_LIVE)?MENU_DELETE:(g.menuMode==MENU_DELETE)?MENU_NAME:MENU_LIVE;
}

static void startNameEdit(void)
{
    loadName(g.st.sel_ch);
    g.namePos=0u; while(g.namePos<NAME_LEN-1u && g.name[g.namePos]) g.namePos++;
    g.nameKey=0xFFu; g.nameTap=0u; g.upper=true; g.nameEdit=true; g.menuMode=MENU_NONE;
}

static void finishNameEdit(bool save)
{
    if(save) A->fm_name_save(g.st.sel_ch,g.name,NAME_LEN);
    g.nameEdit=false; g.nameKey=0xFFu;
}

static void nameDigit(uint8_t key, bool numeric)
{
    static const char map[10][5] = {" 0",".,1","ABC2","DEF3","GHI4","JKL5","MNO6","PQRS","TUV8","WXYZ"};
    uint32_t now=A->ticks_ms();
    uint8_t count=0u; while(count<5u && map[key][count]) count++;
    if(numeric){
        if(g.namePos<NAME_LEN-1u){ g.name[g.namePos++]=(char)('0'+key); g.name[g.namePos]='\0'; }
        g.nameKey=0xFFu; return;
    }
    if(g.nameKey==key && g.namePos>0u && now-g.nameTick<900u){
        g.nameTap=(uint8_t)((g.nameTap+1u)%count);
        char c=map[key][g.nameTap];
        if(!g.upper && c>='A'&&c<='Z') c=(char)(c+32);
        g.name[g.namePos-1u]=c;
    } else if(g.namePos<NAME_LEN-1u){
        g.nameKey=key; g.nameTap=0u;
        char c=map[key][0]; if(!g.upper&&c>='A'&&c<='Z') c=(char)(c+32);
        g.name[g.namePos++]=c; g.name[g.namePos]='\0';
    }
    g.nameTick=now;
}

/* ---- MENU: GOGUFW Live RSSI / save / name / delete ---- */
static void menu(void)
{
    g.inIdx=0;
    if(g.askSave){
        g.ch[g.savePos]=g.st.freq_playing;
        char n[NAME_LEN],*o=n; o=put_t(o,T_CH); o=num2(o,(uint8_t)(g.savePos+1u)); *o='\0';
        A->fm_name_save(g.savePos,n,NAME_LEN); g.askSave=false; return;
    }
    if(g.menuMode==MENU_NONE){ g.menuMode=MENU_LIVE; return; }
    if(g.menuMode==MENU_LIVE){ g.liveChoice=g.liveRssi; g.liveEdit=true; g.menuMode=MENU_NONE; return; }
    if(g.menuMode==MENU_SAVE){ g.askSave=true; g.menuMode=MENU_NONE; return; }
    if(g.menuMode==MENU_NAME){ startNameEdit(); return; }
    if(g.menuMode==MENU_DELETE){
        A->fm_name_save(g.st.sel_ch,"",1u); g.ch[g.st.sel_ch]=0xFFFF;
        g.menuMode=MENU_NONE; configChannel(); tune(); invalidateRssi();
    }
}

/* ---- UP/DOWN: tune (VFO) or channel step (MR) ---- */
static void upDown(int8_t step)
{
    if(g.scanState){ g.scanState=step; scanTuneNext(); return; }   /* continue scan, new direction */
    if(g.askSave){
        if(step>0){ if(++g.savePos>=CHMAX) g.savePos=0; }
        else g.savePos=g.savePos?(uint8_t)(g.savePos-1u):(uint8_t)(CHMAX-1u);
        return;
    }
    if(g.menuMode!=MENU_NONE){ menuMove(step); return; }
    if(g.st.is_mr){
        uint8_t c=findNext((uint8_t)(g.st.sel_ch+step),step);
        if(c!=0xFF && c!=g.st.sel_ch){ g.st.sel_ch=c; g.st.freq_playing=g.ch[c]; tune(); invalidateRssi(); }
    } else {
        g.st.sel_freq=wrap((uint16_t)(g.st.sel_freq+step));
        g.st.freq_playing=g.st.sel_freq; tune(); invalidateRssi();
    }
}

static void toggleMr(void)
{
    g.st.is_mr=!g.st.is_mr;
    if(configChannel()!=0){ /* no valid channel: stayed VFO */ }
    tune();
    invalidateRssi();
    g.askSave=g.askDelete=false; g.inIdx=0;
}

static void cycleBand(void)
{
    g.st.band=(uint8_t)((g.st.band+1)&3u); bandLimits();
    if(g.st.freq_playing<g.lo||g.st.freq_playing>g.hi){ g.st.freq_playing=g.lo; g.st.sel_freq=g.lo; }
    tune();
    invalidateRssi();
}
/* F+key and long-press functions (band / VFO<->MR / auto-scan / quit). */
static void func(uint8_t key)
{
    switch(key){
        case APP_KEY_0:    g.running=false; break;
        case APP_KEY_1:    cycleBand(); break;
        case APP_KEY_3:    toggleMr(); break;
        case APP_KEY_STAR: g.autoConfirm=true; break;
        default: break;
    }
}
static void onShort(uint8_t key)
{
    if(g.nameEdit){
        if(key<=APP_KEY_9) nameDigit(key,false);
        else if(key==APP_KEY_MENU) finishNameEdit(true);
        else if(key==APP_KEY_EXIT) finishNameEdit(false);
        else if(key==APP_KEY_STAR && g.namePos<NAME_LEN-1u){ g.name[g.namePos++]=' '; g.name[g.namePos]='\0'; }
        else if(key==APP_KEY_F) g.upper=!g.upper;
        return;
    }
    if(g.liveEdit){
        if(key==APP_KEY_UP||key==APP_KEY_DOWN) g.liveChoice=!g.liveChoice;
        else if(key==APP_KEY_MENU){ g.liveRssi=g.liveChoice; A->fm_live_rssi(&g.liveRssi,true); g.liveEdit=false; invalidateRssi(); }
        else if(key==APP_KEY_EXIT) g.liveEdit=false;
        return;
    }
    if(g.autoConfirm){
        if(key==APP_KEY_MENU||key==APP_KEY_STAR){ g.autoConfirm=false; startAuto(); }
        else if(key==APP_KEY_EXIT) g.autoConfirm=false;
        return;
    }
    if(key==APP_KEY_F){ g.fArm=!g.fArm; return; }
    if(g.fArm){ g.fArm=false; func(key); return; }    /* F + key */
    if(key<=APP_KEY_9){ digit(key); return; }
    switch(key){
        case APP_KEY_UP:
        case APP_KEY_DOWN: upDown(A->nav_dir(key)); break;
        case APP_KEY_STAR: startManual(+1); break;
        case APP_KEY_MENU: menu(); break;
        case APP_KEY_EXIT:
            if(g.inIdx) g.inIdx--;
            else if(g.askSave||g.askDelete||g.menuMode!=MENU_NONE) g.askSave=g.askDelete=false,g.menuMode=MENU_NONE;
            else g.running=false;
            break;
        default: break;
    }
}
static void onLong(uint8_t key)
{
    if(g.nameEdit && key<=APP_KEY_9){ nameDigit(key,true); return; }
    g.fArm=false; func(key);
}

__attribute__((section(".text.entry"),used))
void app_main(const app_api_t *api)
{
    A=api;
    A->backlight_on();
    g.ch=A->fm_channels;
    A->fm_state(&g.st,false);        /* inherit the resident FM state */
    A->fm_live_rssi(&g.liveRssi,false);
    if(g.st.band>3) g.st.band=0;
    bandLimits();
    if(g.st.freq_playing<g.lo||g.st.freq_playing>g.hi) g.st.freq_playing=g.lo;
    if(g.st.sel_freq<g.lo||g.st.sel_freq>g.hi) g.st.sel_freq=g.st.freq_playing;
    if(g.st.is_mr) configChannel();
    /* askSave, askDelete, fArm, inIdx and savePos start zeroed (.bss) */

    A->fm_enter(g.st.freq_playing,g.st.band);
    invalidateRssi();
    sampleRssi();
    g.rssiTick=A->ticks_ms();

    /* short = on release (held < ~0.5 s) · long = at the 0.5 s threshold ·
       UP/DOWN = immediate step on press, then auto-repeat while held. */
    g.running=true;
    uint8_t  held=APP_KEY_INVALID;
    uint16_t heldMs=0;
    bool     firedLong=false;
    bool     dirty=true;                               /* redraw only on change */

    while(g.running){
        uint8_t key=A->get_key();
        bool rep=(key==APP_KEY_UP||key==APP_KEY_DOWN);

        if(key==APP_KEY_SAVER){
            held=APP_KEY_INVALID; heldMs=0; firedLong=false;
            A->delay_ms(10); A->backlight_update();
            continue;
        } else if(key==APP_KEY_WAKE||key==APP_KEY_PTT){
            held=APP_KEY_INVALID; heldMs=0; firedLong=false; dirty=true;
        } else if(key==APP_KEY_INVALID){
            if(held!=APP_KEY_INVALID && !firedLong &&
               held!=APP_KEY_UP && held!=APP_KEY_DOWN){
                onShort(held); dirty=true;
            }
            held=APP_KEY_INVALID; heldMs=0; firedLong=false;
        } else if(key!=held){
            A->backlight_on();
            held=key; heldMs=0; firedLong=false;
            if(rep){ onShort(key); dirty=true; }       /* immediate first step */
        } else {
            heldMs=(uint16_t)(heldMs+50u);
            if(rep){
                if(heldMs>=300){ onShort(held); dirty=true; }   /* auto-repeat */
            } else if(!firedLong && heldMs>=400){
                firedLong=true; onLong(held); dirty=true;
            }
        }

        /* non-blocking scan: one step each time the settle timer expires */
        if(g.scanState){
            /* Match resident FM: an active scan keeps the display awake. */
            A->backlight_on();
            if(g.scanTimer<=50) scanStep();
            else g.scanTimer=(uint16_t)(g.scanTimer-50);
            dirty=true;
        }

        if(!g.scanState && (g.liveRssi || g.rssiLevel==0xFFu) &&
           A->ticks_ms()-g.rssiTick>=250u){
            uint8_t old=g.rssiLevel; sampleRssi(); g.rssiTick=A->ticks_ms();
            if(old!=g.rssiLevel) dirty=true;
        }

        if(dirty){ show(); dirty=false; }
        /* Keep the resident 10 ms fade cadence while retaining this app's
         * existing 50 ms key/scan state-machine tick. */
        for(uint8_t i=0;i<5u;i++){
            A->delay_ms(10);
            A->backlight_update();
        }
    }

    /* push our state back to the resident FM and persist (config + 48 channels) */
    if(!g.st.is_mr) g.st.sel_freq=g.st.freq_playing;
    A->fm_state(&g.st,true);
    A->fm_commit();
    A->fm_exit();
}
